import dash
from dash import html, dcc
import dash_bootstrap_components as dbc
import base64

dash.register_page(__name__, path='/', order=0)


image_filename = 'assets/my_pic.jpg' # replace with your own image
encoded_image = base64.b64encode(open(image_filename, 'rb').read())

# resume sample template from https://zety.com/
layout = html.Div([
    dcc.Markdown('# Hyungju Lee', style={'textAlign':'center'}),
    dcc.Markdown('Toronto, Canada', style={'textAlign': 'center'}),

    dbc.Row(html.Img(src='data:image/png;base64,{}'.format(encoded_image.decode()), 
                     style={'height':'40%', 'width':'40%', 'margin':'auto', 'padding':'2rem'}), 
                     justify='center'),
    
    dcc.Markdown('## AI Researcher / Computer Vision Engineer', style={'textAlign': 'center'}),
    html.Hr(),
    dcc.Markdown('A pro-active, MSc. professional with award-winning proficiency in programming skills and \n'
                 'over 3 years’ experience in object detection and use of geospatial tools related \n'
                 'to deep learning. As a collaborative lead and learner, I am seeking to leverage my \n'
                 'engineering skills, technical skills, and R & D experience.',
                 style={'textAlign': 'center', 'white-space': 'pre'}),

    dcc.Markdown('### Skills', style={'textAlign': 'center'}),
    html.Hr(),
    dbc.Row([
        dbc.Col([
            dcc.Markdown('''
            * Python 
            * SQL
            * R
            ''')
        ], width={"size": 2, "offset": 0}),
        dbc.Col([
            dcc.Markdown('''
            * MatLab
            * Terrascan
            * ArcGIS
            ''')
        ], width=2),
        dbc.Col([
            dcc.Markdown('''
            * Creativity & Problem Solving
            * Written & Oral Communication
            * Teamwork
            ''')
        ], width=3)
    ], justify='center'),

    dcc.Markdown('### Experience', style={'textAlign': 'center'}),
    html.Hr(),

    dbc.Row([
        dbc.Col([
            dcc.Markdown('2019 to current', style={'textAlign': 'center'})
        ], width=3),
        dbc.Col([
            dcc.Markdown('Researcher \n'
                         'AUSM Lab - Toronto, Canada',
                         style={'white-space': 'pre'},
                         className='ms-3'),
            html.Ul([
                html.Li(
                    'Publication and presentation at International Conference on Pattern Recognition (ICPR) introducing a novel large-scale airborne lidar system (ALS) dataset with single tree annotations for over 5,000 boxes, a benchmark generated by applying different object detection networks.'),
                html.Li(
                    'Accomplished domain transformation of all point cloud data from 3D to 2D for $10 million Ontario Train Autonomy Collaboration (OnTRAC) project.'),
                html.Li(
                    'Ensured strict adherence to changing priorities with colleagues and stakeholders.'),
            ])
        ], width=8)
    ], justify='center'),

    dbc.Row([
        dbc.Col([
            dcc.Markdown('2015 to 2022',
                         style={'textAlign': 'center'})
        ], width=3),
        dbc.Col([
            dcc.Markdown('Teaching Assistant \n'
                         'York University / University of Toronto MSLC - Toronto, Canada',
                         style={'white-space': 'pre'},
                         className='ms-3'),
            html.Ul([
                html.Li(
                    'Led tutorials, lab sessions, exam preparation sessions, math and statistics help center and many more activities as a teaching assistant for multiple professors and departments.'),
                html.Li(
                    'Exemplified exceptional professionalism and time management skills working 25 hours a week in addition to fulfilling research degree requirements.'),
                html.Li(
                    'Facilitated R, Python, SQL, MATLAB, ArcGIS and Terrascan learning sessions for students and faculty members.'),
            ])
        ], width=8)
    ], justify='center'),

    dbc.Row([
        dbc.Col([
            dcc.Markdown('2017 to 2018',
                         style={'textAlign': 'center'})
        ], width=3),
        dbc.Col([
            dcc.Markdown('Financial Analyst \n'
                         'Ontario Ministry of Natural Resources and Forestry, Land and Resource - Peterborough, Canada',
                         style={'white-space': 'pre'},
                         className='ms-3'),
            html.Ul([
                html.Li(
                    'Investigated and participated in automation projects and tasks related to all divisions of the Ministry. Managed over $5 million for technical equipments and human resource budgets control.'),
                html.Li(
                    'Developed a new format for financial reports that pulls specific financial data from Oracle Database automatically, provided training and consultancy for project managers and senior leadership to use. Training sessions held in Sudbury, Guelph, and Peterborough.'),
            ])
        ], width=8)
    ], justify='center'),

    dbc.Row([
        dbc.Col([
            dcc.Markdown('2015 to 2016',
                         style={'textAlign': 'center'})
        ], width=3),
        dbc.Col([
            dcc.Markdown('Research Assistant \n'
                         'University of Toronto MSLC - Toronto, Canada',
                         style={'white-space': 'pre'},
                         className='ms-3'),
            html.Ul([
                html.Li(
                    'Manipulated and analyzed data collected from each student service center for researching center service usage and efficiency.'),
                html.Li(
                    'Documented procedures and workflows used at the center and presented to high school teachers from China, how alternative software such as R would be beneficial. The goal was to transfer knowledge to partner stakeholders associated with the university.'),
            ])
        ], width=8)
    ], justify='center'),

    dbc.Row([
        dbc.Col([
            dcc.Markdown('2015 to 2016',
                         style={'textAlign': 'center'})
        ], width=3),
        dbc.Col([
            dcc.Markdown('Student Mentor \n'
                         'York University - Toronto, Canada',
                         style={'white-space': 'pre'},
                         className='ms-3'),
            html.Ul([
                html.Li(
                    'Successfully led a team of undergraduate students through the Data-Centric AI object detection competition that required optimizing detection algorithms and dataset annotation.'),
                html.Li(
                    'Mentored students have gone on to secure jobs at Ontario Ministry of Transportation, Winterlight Labs and Terra Remote Sensing.'),
            ])
        ], width=8)
    ], justify='center'),

    dcc.Markdown('### Education', style={'textAlign': 'center'}),
    html.Hr(),

    dbc.Row([
        dbc.Col([
            dcc.Markdown('2022',
                         style={'textAlign': 'center'})
        ], width=3),
        dbc.Col([
            dcc.Markdown('Masters in Earth and Space Science & Engineering\n'
                         'York University - Toronto, Canada',
                         style={'white-space': 'pre'},
                         className='ms-3'),
        ], width=8),
    ], justify='center'),

    dbc.Row([
        dbc.Col([
            dcc.Markdown('2020',
                         style={'textAlign': 'center'})
        ], width=3),
        dbc.Col([
            dcc.Markdown('Honours Bachelor of Science in Statistics, \n'
                         'Specialist (Co-operative) Program in Statistics- Quantitative Finance Stream\n'
                         'University of Toronto - Toronto, Canada',
                         style={'white-space': 'pre'},
                         className='ms-3')
        ], width=8)
    ], justify='center')
])
